server {
    listen 80;
    server_name localhost;

    # 静态资源请求 (模拟前端文件)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 动态业务请求反向代理到后端 (05-Nginx 核心)
    # 当检测到这个路径，Nginx 就变成前台服务员，把单子丢给后厨(backend)
    location /api/ {
        # 注意：这里用的 backend_api 是 docker-compose 中的服务名，体现了 Docker 内网 DNS 的威力
        proxy_pass http://backend_api:8080/;
        
        # 传递客户端真实 IP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # 超时设置（这是你面试答 504 Gateway Timeout 的底气）
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }

    # 定制化错误页面，优雅处理后端挂掉的情况 (502/504)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
